[package]
name = "tasker"
version = "0.1.0"
authors = ["Michal Dunajski <michaldunajski2505@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
