title = "Task list"

[[task]]
subject = "Shopping"
message = "Sugar, flour, other stuff"

[[task]]
subject = "Cleaning"
message = "floor"

[[task]]
subject = "Example Subject from terminal"
message = "Example Message from terminal"

[[task]]
subject = "Add another task after auto count"
message = "Check that is fine?"
